[package]
name = "ritelinked"
version = "0.1.0"
authors = ["Chojan Shang <psiace@outlook.com>"]
edition = "2018"
description = "HashMap-like containers that hold their key-value pairs in a user controllable order"
repository = "https://github.com/ritedb/ritelinked"
documentation = "https://docs.rs/ritelinked"
readme = "README.md"
keywords = ["data-structures"]
license = "MIT OR Apache-2.0"

[features]
default = ["amortized"]
serde_impl = ["serde"]
amortized = ["griddle"]

[dependencies]
hashbrown = "0.9.0"
griddle = { version = "0.4.1", optional = true }
serde = { version = "1.0", optional = true }

[dev-dependencies]
serde_test = "1.0"
